name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache sonar scanner
      uses: actions/cache@v4
      with:
        path: ~/.sonar
        key: sonar-scanner-${{ runner.os }}-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          sonar-scanner-${{ runner.os }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests and generate coverage report
      run: |
        pytest --cov=src --cov-report=xml:coverage.xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_SCANNER_OPTS: "-Dsonar.python.coverage.reportPaths=coverage.xml"
