name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK (required by SonarCloud for Java projects)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Set Java version to 11
          distribution: 'adoptopenjdk'  # Add this line to specify the distribution

      # Clean repository to ensure there are no issues with Git state
      - name: Clean repository
        run: |
          git reset --hard
          git clean -fdx

      # Install SonarScanner
      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-4.7.0.2747-linux.zip
          unzip sonar-scanner-4.7.0.2747-linux.zip
          sudo mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # Run SonarCloud analysis
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=RoyalEnfieldAuctionHub \
            -Dsonar.organization=SRIVASTAVAREDDYMADAPA \
            -Dsonar.host.url=https://sonarcloud.io
