name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: amazon-linux-2  # Using Amazon Linux 2

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment (version 3.8 in this case)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          # Upgrade pip to the latest version
          python -m pip install --upgrade pip
          
          # Install dependencies from requirements.txt
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found!"
            exit 1
          fi

      # Step 4: Run Django tests
      - name: Run tests
        run: python manage.py test
