name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Set PYTHONPATH to include src directory
      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV  # Adds src to PYTHONPATH

    - name: Run tests with coverage
      run: |
        pytest --cov=src --cov-report=xml  # Specify 'src' to collect coverage data

    - name: SonarCloud Scan
      run: sonar-scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
