name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonarcloud:
  build:
    name: Build and Analyze on SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
      # Step to Checkout the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v3
      # Set up JDK (required by SonarCloud for Java projects)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      # Install SonarScanner (this is the step that was missing)
      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-4.7.0.2747-linux.zip
          unzip sonar-scanner-4.7.0.2747-linux.zip
          sudo mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
      # Step to Run SonarCloud Analysis
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Make sure you have added your SONAR_TOKEN in GitHub Secrets
        run: |
          sonar-scanner \
            -Dsonar.organization="SRIVASTAVAREDDYMADAPA" \
            -Dsonar.projectKey="RoyalEnfieldAuctionHub" \
            -Dsonar.sources="." 
            -Dsonar.projectKey=RoyalEnfieldAuctionHub \
            -Dsonar.organization=SRIVASTAVAREDDYMADAPA \
            -Dsonar.host.url=https://sonarcloud.io
